## ○ 빅데이터 분석기초_안나경

### 1. 데이터 관리

In [2]:
import matplotlib

# 맑은 고딕 적용
matplotlib.rc("font", family = "Malgun Gothic")
# 음수 표시
matplotlib.rc('axes', unicode_minus=False)

In [3]:
# 실행결과 경고메시지 출력 제외
import warnings

warnings.filterwarnings('ignore')

In [4]:
# 8 Page (데이터 구조 연습)
#데이터 생성
import pandas as pd         # pd: 약어로 명명

#Series 구조로 변환
dict_data = {'a': 1, 'b': 2, 'c': 3}
sr = pd.Series(dict_data)
print(type(sr))
print(sr)

<class 'pandas.core.series.Series'>
a    1
b    2
c    3
dtype: int64

#### 인덱스 첫번째 값은 0부터 시작한다

In [5]:


table = {"일자" : ['2019-01-01', '2018-01-04', '2019-01-07'], 
         "가격" : [1000, 2000, 3000], 
         "구매여부" : ['F', 'T', 'F'],
         "제품": ['사이다', '콜라', '도너츠']}
df = pd.DataFrame(table)

df      # 판다스(Pandas) 데이터프레임이 가진 HTML 서식이 적용
#print(df) : 데이터를 순수한 텍스트(Text) 형태로 출력 (데이터프레임X)

           일자    가격 구매여부   제품
0  2019-01-01  1000    F  사이다
1  2018-01-04  2000    T   콜라
2  2019-01-07  3000    F  도너츠

1. Key (키) = Column Name (컬럼명)
2. Value (값) = Series (데이터 목록)
3. Row (행) = Instance / Record (인스턴스)

#### 행 인덱스 설정 (Row Index Assignment)

In [6]:
df1 = pd.DataFrame(table, index= ['a', 'b', 'c'])

df1

           일자    가격 구매여부   제품
a  2019-01-01  1000    F  사이다
b  2018-01-04  2000    T   콜라
c  2019-01-07  3000    F  도너츠

In [8]:
# csv는 인코딩을 해주도록 합시다.
# 인코딩 종류 :  utf-8, cp949, euc-kr
df = pd.read_csv(r"D:\BigData_수업용\2605619_33기 AI·Big Data 실습 파일, 연습 코드\1. Big Data 분석 기초 실습파일\FITNESS.csv", encoding = 'euc-kr')
df.tail()           # 하위 5개 행을 보여줍니다.

,NAME,GENDER,AGE,AGEGROUP,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
26,Iris,여성,39,30대,75.98,45.681,11.95,176,70,180
27,Mark,남성,57,50대,73.37,39.407,12.63,174,58,176
28,Steve,남성,54,50대,91.63,39.203,12.88,168,44,172
29,Vaughn,남성,44,40대,81.42,39.442,13.08,174,63,176
30,William,남성,45,40대,87.66,37.388,14.03,186,56,192

In [9]:
# excel은 인코딩을 해주지 않아도 됩니다. 시트 단위로 나눠져있기 때문에 뭘 불러올건지 설정해야합니다.
df = pd.read_excel(r"D:\BigData_수업용\2605619_33기 AI·Big Data 실습 파일, 연습 코드\1. Big Data 분석 기초 실습파일\성적처리.xlsx", sheet_name = 'Sheet1')
df.head()

    반   성명  국어  영어  수학  사회  과학
0  1반  홍길동  93  80  94  73  64
1  5반  백일홍  93  63  76  84  92
2  3반  이삼상  94  74  86  90  70
3  4반  정말로  83  55  64  90  65
4  5반  한번도  87  95  66  75  60

In [10]:
# 13 Page
table = {"일자" : ['2019-01-01', '2019-01-04', '2019-01-07', '2019-01-10', '2019-01-13'],
        "가격" : [1000, 1500, 2000, 2500, 3000],
        "구매여부" : ['False', 'True', 'True', 'True', 'True'],
        "제품" : ['gum', 'snack', 'beverage', 'dongas', 'alchoal']}
df = pd.DataFrame(table)
df

           일자    가격   구매여부        제품
0  2019-01-01  1000  False       gum
1  2019-01-04  1500   True     snack
2  2019-01-07  2000   True  beverage
3  2019-01-10  2500   True    dongas
4  2019-01-13  3000   True   alchoal

### 앞서 작업한(13 Page) 데이터프레임(df)을 지정된 경로에 각각 CSV와 엑셀 파일로 저장하는 명령어

In [ ]:
df.to_csv("/home/piai/제품명세.csv", encoding="euc-kr")     #경로는 임의 설정
df.to_excel("/home/piai/제품명세.xlsx", index=False)

In [ ]:
df.to_csv("C:/청년AI.BigData아카데미/data/제품명세.csv")
df.to_excel("C:/청년AI.BigData아카데미/data/제품명세.xlsx")

In [ ]:
df.to_csv("C:/청년AI.BigData아카데미/data/제품명세.csv", encoding = "euc-kr")
df.to_excel("C:/청년AI.BigData아카데미/data/제품명세.xlsx", encoding = "euc-kr", index = False)



### 1. CSV 파일을 메모장이나 일반 에디터로 열었을 때

encoding 옵션 없이 저장하면 리눅스 환경의 기본값인 UTF-8로 저장됩니다. 이걸 인코딩을 맞추지 않고 열면 다음과 같이 보여야 합니다.

    의도된 결과 (깨짐):  ÀÏÀÚ,°¡°Ý,±¸¸Å¿©ºÎ,Á¦Ç°  (또는 한글이 아예 ``로 표시됨)

    왜?: 컴퓨터가 "이건 A라는 규칙(EUC-KR)으로 읽어야 해"라고 생각하는데, 실제 데이터는 B라는 규칙(UTF-8)으로 적혀 있어서 번역기 오류가 난 상태입니다.

### 2. 엑셀에서 CSV 파일을 열었을 때 

윈도우용 엑셀은 기본적으로 한글을 CP949(EUC-KR 계열)로 읽으려고 시도합니다.

    인코딩 설정 없이(utf-8) 저장한 경우: 엑셀에서 열면 한글이 전부 뱡뱡뱡이나 외계어로 깨져서 나옵니다.

    encoding='euc-kr'로 저장한 경우: 엑셀에서 열었을 때 한글이 깨끗하게 나와야 합니다.



*만약 to_excel 명령어 실행 시 TypeError: ... unexpected keyword argument 'encoding'이라는 에러가 발생한다면, 그건 사용 중인 판다스 버전이 높아서 엑셀 저장 시 인코딩 옵션이 필요 없기 때문입니다.

## **윈도우 환경에서 실습중 ...

In [11]:
#실습환경 설정
#pip install numpy==1.23.5 pandas==1.5.3 scikit-learn==1.2.1 matplotlib==3.7.0 seaborn==0.12.2 mlxtend==0.23.1 xgboost==1.6.2 lightgbm==3.3.3 yellowbrick==1.4
import pandas as pd
import numpy as np
print(f"Pandas 버전: {pd.__version__}")
print(f"NumPy 버전: {np.__version__}")

Pandas 버전: 2.2.2
NumPy 버전: 1.26.4

In [15]:
# 18 Page (데이터 내용 확인 연습)
df = pd.read_csv(r'D:\BigData_수업용\2605619_33기 AI·Big Data 실습 파일, 연습 코드\1. Big Data 분석 기초 실습파일\auto_mpg.csv', encoding = 'utf-8')
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,modelyear,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

In [16]:
df.tail()

,mpg,cylinders,displacement,horsepower,weight,acceleration,modelyear,origin,name
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [17]:
# 19 Page
# 열과 행의 개수 확인
df.shape

(398, 9)

In [18]:
# 열의 속성 확인
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    398 non-null    object
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   modelyear     398 non-null    int64
 7   origin        398 non-null    int64
 8   name          398 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.1+ KB

In [19]:
# 열의 속성 확인
df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower       object
weight            int64
acceleration    float64
modelyear         int64
origin            int64
name             object
dtype: object

In [20]:
#
df.mpg.dtypes

dtype('float64')

In [21]:
# 요약정보 확인
df.describe()

,mpg,cylinders,displacement,weight,acceleration,modelyear,origin
count,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000,398.000000
mean,23.514573,5.454774,193.425879,2970.424623,15.568090,76.010050,1.572864
std,7.815984,1.701004,104.269838,846.841774,2.757689,3.697627,0.802055
min,9.000000,3.000000,68.000000,1613.000000,8.000000,70.000000,1.000000
25%,17.500000,4.000000,104.250000,2223.750000,13.825000,73.000000,1.000000
50%,23.000000,4.000000,148.500000,2803.500000,15.500000,76.000000,1.000000
75%,29.000000,8.000000,262.000000,3608.000000,17.175000,79.000000,2.000000
max,46.600000,8.000000,455.000000,5140.000000,24.800000,82.000000,3.000000

In [22]:
# 21 Page
# 데이터의 개수 확인
print(df.count())

mpg             398
cylinders       398
displacement    398
horsepower      398
weight          398
acceleration    398
modelyear       398
origin          398
name            398
dtype: int64

In [23]:
# 데이터프레임 df의 특정 열이 가지고 있는 고유값 확인 
unique_values = df['origin'].value_counts() 
unique_values

origin
1    249
3     79
2     70
Name: count, dtype: int64

In [24]:
# cylinders수를 기준으로 데이터들의 평균 확인
df.groupby(["cylinders"],as_index=False).mean()

TypeError: agg function failed [how->mean,dtype->object]

1. 에러의 원인: numeric_only 옵션의 부재
질문자님의 데이터프레임(df) 안에는 '자동차 이름(name)'이나 '마력(horsepower)'처럼 문자열(object)로 된 열들이 섞여 있을 거예요.

과거 버전: "에이, 문자열은 내가 알아서 빼고 숫자만 평균 내줄게~" 하고 넘어갔습니다.

최신 버전: "너 문자열 열도 있는데 이거 포함해서 평균 낼 거야? 아니면 뺄 거야? 확실히 정해!(numeric_only=True를 써!)"라며 에러를 던집니다.

2. 해결 방법: 코드 수정
아래와 같이 numeric_only=True 옵션을 추가해 주시면 바로 해결됩니다.  

옵션 설명: 데이터프레임 내에서 문자열 같은 비수치 데이터를 제외하고, 산술 계산이 가능한 숫자 데이터만 골라 연산을 수행하도록 제한하는 옵션

In [25]:
# 숫자인 데이터만 계산하라고 명시해줘야 합니다.
df.groupby(["cylinders"], as_index=False).mean(numeric_only=True)

,cylinders,mpg,displacement,weight,acceleration,modelyear,origin
0,3,20.550000,72.500000,2398.500000,13.250000,75.500000,3.000000
1,4,29.286765,109.796569,2308.127451,16.601471,77.073529,1.985294
2,5,27.366667,145.000000,3103.333333,18.633333,79.000000,2.000000
3,6,19.985714,218.142857,3198.226190,16.263095,75.928571,1.190476
4,8,14.963107,345.009709,4114.718447,12.955340,73.902913,1.000000

In [26]:
# cylinders수를 기준으로 중량, 가속시간 평균
df.groupby(["cylinders"], as_index=False)[['weight', 'acceleration']].mean()

   cylinders       weight  acceleration
0          3  2398.500000     13.250000
1          4  2308.127451     16.601471
2          5  3103.333333     18.633333
3          6  3198.226190     16.263095
4          8  4114.718447     12.955340

In [ ]:
# 22 Page
# 년도, cylinders수를 기준으로 데이터의 평균 확인
df.groupby(['modelyear', 'cylinders'],as_index=False).mean(numeric_only=True)

,modelyear,cylinders,mpg,displacement,weight,acceleration,origin
0,70,4,25.285714,107.000000,2292.571429,16.000000,2.285714
1,70,6,20.500000,199.000000,2710.500000,15.500000,1.000000
2,70,8,14.111111,367.555556,3940.055556,11.194444,1.000000
3,71,4,27.461538,101.846154,2056.384615,16.961538,1.923077
4,71,6,18.000000,243.375000,3171.875000,14.750000,1.000000
5,71,8,13.428571,371.714286,4537.714286,12.214286,1.000000
6,72,3,19.000000,70.000000,2330.000000,13.500000,3.000000
7,72,4,23.428571,111.535714,2382.642857,17.214286,1.928571
8,72,8,13.615385,344.846154,4228.384615,13.000000,1.000000
9,73,3,18.000000,70.000000,2124.000000,13.500000,3.000000
10,73,4,22.727273,109.272727,2338.090909,17.136364,2.000000
11,73,6,19.000000,212.250000,2917.125000,15.687500,1.250000
12,73,8,13.200000,365.250000,4279.050000,12.250000,1.000000
13,74,4,27.800000,96.533333,2151.466667,16.400000,2.200000
14,74,6,17.857143,230.428571,3320.000000,16.857143,1.000000
15,74,8,14.200000,315.200000,4438.400000,14.700000,1.000000
16,75,4,25.250000,114.833333,2489.250000,15.833333,2.166667
17,75,6,17.583333,233.750000,3398.333333,17.708333,1.000000
18,75,8,15.666667,330.500000,4108.833333,13.166667,1.000000
19,76,4,26.766667,106.333333,2306.600000,16.866667,1.866667
20,76,6,20.000000,221.400000,3349.600000,17.000000,1.300000
21,76,8,14.666667,324.000000,4064.666667,13.222222,1.000000
22,77,3,21.500000,80.000000,2720.000000,13.500000,3.000000
23,77,4,29.107143,106.500000,2205.071429,16.064286,1.857143
24,77,6,19.500000,220.400000,3383.000000,16.900000,1.400000
25,77,8,16.000000,335.750000,4177.500000,13.662500,1.000000
26,78,4,29.576471,112.117647,2296.764706,16.282353,2.117647
27,78,5,20.300000,131.000000,2830.000000,15.900000,2.000000
28,78,6,19.066667,213.250000,3314.166667,16.391667,1.166667
29,78,8,19.050000,300.833333,3563.333333,13.266667,1.000000
30,79,4,31.525000,113.583333,2357.583333,15.991667,1.583333
31,79,5,25.400000,183.000000,3530.000000,20.100000,2.000000
32,79,6,22.950000,205.666667,3025.833333,15.433333,1.000000
33,79,8,18.630000,321.400000,3862.900000,15.400000,1.000000
34,80,3,23.700000,70.000000,2420.000000,12.500000,3.000000
35,80,4,34.612000,111.000000,2360.080000,17.144000,2.200000
36,80,5,36.400000,121.000000,2950.000000,19.900000,2.000000
37,80,6,25.900000,196.500000,3145.500000,15.050000,2.000000
38,81,4,32.814286,108.857143,2275.476190,16.466667,2.095238
39,81,6,23.428571,184.000000,3093.571429,15.442857,1.714286
40,81,8,26.600000,350.000000,3725.000000,19.000000,1.000000
41,82,4,32.071429,118.571429,2402.321429,16.703571,1.714286
42,82,6,28.333333,225.000000,2931.666667,16.033333,1.000000

In [30]:
# 년도, cylinders수를 기준으로 데이터의 평균, 중앙값 확인
df.groupby(['modelyear', 'cylinders']).agg(['mean', 'median']).mean(numeric_only=True)

TypeError: agg function failed [how->mean,dtype->object]

### 데이터 선택

In [31]:
# 28 Page (데이터선택 연습)
import pandas as pd
# numpy: 숫자 연산용
import numpy as np
# random 함수 
from numpy.random import randn

In [32]:
# 샘플 데이터 통일을 위해 seed 고정: 1234
np.random.seed(1234)
# 랜덤 함수를 이용해 df데이터 생성 
df = pd.DataFrame(randn(10,2), columns=['A','B']) 
df

          A         B
0  0.471435 -1.190976
1  1.432707 -0.312652
2 -0.720589  0.887163
3  0.859588 -0.636524
4  0.015696 -2.242685
5  1.150036  0.991946
6  0.953324 -2.021255
7 -0.334077  0.002118
8  0.405453  0.289092
9  1.321158 -1.546906

In [33]:
# 31 Page
# 열 선택: Series 반환
df['A']

0    0.471435
1    1.432707
2   -0.720589
3    0.859588
4    0.015696
5    1.150036
6    0.953324
7   -0.334077
8    0.405453
9    1.321158
Name: A, dtype: float64

In [34]:
# 열 선택: DataFrame 반환  
df[['A']]

          A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696
5  1.150036
6  0.953324
7 -0.334077
8  0.405453
9  1.321158

| **구분** | **문법 예시** | **범위 규칙** | **선택 기준** | **특징** |
| --- | --- | --- | --- | --- |
| **기본 슬라이싱** | `df[0:5]` | **미만** (0~4) | **위치(순서)** | 행(Row)만 선택 가능 |
| **loc** | `df.loc[0:5]` | **이하 (0~5)** | **이름(Label)** | 눈에 보이는 **이름** 기준 (끝점 포함) |
| **iloc** | `df.iloc[0:5]` | **미만** (0~4) | **위치(Index)** | 컴퓨터가 매긴 **순서** 기준 (끝점 제외) |

In [35]:
# 행 선택
df[0:5]

          A         B
0  0.471435 -1.190976
1  1.432707 -0.312652
2 -0.720589  0.887163
3  0.859588 -0.636524
4  0.015696 -2.242685

In [36]:
# 32 Page
# loc: 열과 행을 이름으로 지정 가능
df.loc[0:7,['A']]

          A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696
5  1.150036
6  0.953324
7 -0.334077

In [37]:
# 열 선택: DataFrame 반환  
df.loc[:, ['A']]    # 전체

          A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696
5  1.150036
6  0.953324
7 -0.334077
8  0.405453
9  1.321158

In [38]:
# 행 선택
df.loc[3:8]

          A         B
3  0.859588 -0.636524
4  0.015696 -2.242685
5  1.150036  0.991946
6  0.953324 -2.021255
7 -0.334077  0.002118
8  0.405453  0.289092

In [39]:
# 단일 행 선택
df.loc[3:3]

          A         B
3  0.859588 -0.636524

In [40]:
# 33 Page
# iloc: 열과 행을 index번호로 지정 가능
df.iloc[0:7, [0]]

          A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696
5  1.150036
6  0.953324

In [27]:
# 열 선택: DataFrame 반환  
df.iloc[:, [0]]

          A
0  0.471435
1  1.432707
2 -0.720589
3  0.859588
4  0.015696
5  1.150036
6  0.953324
7 -0.334077
8  0.405453
9  1.321158

In [28]:
# 행 선택
df.iloc[3:8]

          A         B
3  0.859588 -0.636524
4  0.015696 -2.242685
5  1.150036  0.991946
6  0.953324 -2.021255
7 -0.334077  0.002118

In [29]:
# 단일 행 선택
df.iloc[3:4]

          A         B
3  0.859588 -0.636524

### 특정한 조건을 이용한 데이터 선택

In [30]:
# 34 Page
# 조건을 이용한 데이터 선택
df.query('A > 0.5')

          A         B
1  1.432707 -0.312652
3  0.859588 -0.636524
5  1.150036  0.991946
6  0.953324 -2.021255
9  1.321158 -1.546906

In [ ]:
# query 와 동일한 slice 표현
df.query('A > B')

In [ ]:
df[df.A > df.B]

In [ ]:
# 35 Page
# 복수 조건을 이용한 데이터 선택
# AND 조건
df.query( 'A > 0.5 & B < 0.0' )

In [ ]:
# OR 조건
df.query( 'A > 0.5 | B < 0.0' )

### 데이터 선택

- filter :  데이터의 특정 컬럼을 선택하거나 특정 문자를 포함하고 있는 컬럼 선택 밑 데이터 추출
- mask : 조건문이 참(True)인 데이터 포인트들을 골라내어 지정한 값으로 변경하거나 가려버리는(결측치 처리 등) 데이터 변형 함수입니다.

In [ ]:
# 37 Page (데이터선택 연습)
df = pd.DataFrame({'ABC': ['A','B','C','A'], 
                   'abc':['a','b','c','c'],
                   'group1':['G1','G2','G3','G4'],
                   'value1':[11,13,12,14],
                   'val1_mod':[0.231,0.197,0.213, 0.199] })
                   
df

In [ ]:
# 컬럼이름 직접 입력
df.filter(items = ['group1', 'value1', 'val1_mod'])

In [ ]:
# regex(regular express) 이용. ‘1’포함 
df.filter(regex='1', axis=1)

- df.filter: 데이터프레임의 '내용'과는 상관없이, 오직 행/열의 '이름(Label)'만을 기준으로 원하는 부분을 골라내는 함수

- regex='1': 이름 안에 숫자 '1'이 포함된 모든 대상을 찾겠다

- axis=1: 검색 대상을 행(0)이 아닌 열(1, Column)로 지정하여, 이름에 '1'이 들어간 컬럼들을 선택하라는 의미

In [ ]:
# axis=0 (행 방향)
df.filter(regex='1', axis=0)

In [ ]:
# axis=1 (열 방향) : 열 전체가 통째로 추출
df.filter(regex='1', axis=1)

axis=0: "이름(번호)이 1인 사람(행) 다 나와!" $\rightarrow$ 특정 데이터 한 줄 추출  
axis=1: "이름에 1이 들어간 정보(열) 다 가져와!" $\rightarrow$ 특정 속성(컬럼)들만 추출

이런 이런 결과가 나왔는데 이걸 합친 명령어가 뭐냐..?

In [ ]:
# regex이용.’1’로 끝나는 컬럼
df.filter(regex='1$', axis=1)

In [ ]:
# 39 Page
# ‘a’ 포함된 컬럼. regex=‘a’와 동일
df.filter(like='a', axis=1)

In [ ]:
# ‘A’ 또는 ‘a’ 포함된 컬럼([ ] 이용)
# 컬럼 이름에 대문자 'A' 또는 소문자 'a'가 포함된 열들을 모두 추출
# 동작: 대괄호 [ ]는 이 안에 있는 글자 중 하나라도 있으면 오케이
df.filter(regex='[Aa]', axis=1)

In [ ]:
# 42 Page
# 조건 입력 및 mask 적용
# 'value1' 값이 12보다 큰 행들을 모두 찾아서 결측치(NaN)로 변경
df.mask(df.value1 > 12 )

In [ ]:
# 'abc' 컬럼 값이 'a'인 행 전체를 NaN(결측치)으로 가려버림
df.mask(df.abc == 'a')

In [ ]:
# 조건 입력 및 mask 적용,
# 조건에 해당되지 않는 값 처리
# 'value1'이 12보다 큰 행 전체를 999로 변경함
df.mask(cond = df.value1 > 12, other = 999)

### 데이터 결합 (CONCAT)

In [ ]:
# 47 Page (데이터결합 연습)
# df1, df2, df3 데이터 생성
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2', 'A3'],
                    'B': ['B0', 'B1', 'B2', 'B3'],
                    'C': ['C0', 'C1', 'C2', 'C3'],
                    'D': ['D0', 'D1', 'D2', 'D3']},
                   index=[0, 1, 2, 3])
df2 = pd.DataFrame({'A': ['A4', 'A5', 'A6', 'A7'],
                    'B': ['B4', 'B5', 'B6', 'B7'],
                    'C': ['C4', 'C5', 'C6', 'C7'],
                    'D': ['D4', 'D5', 'D6', 'D7']},
                   index=[4, 5, 6, 7])
df3 = pd.DataFrame({'A': ['A8', 'A9', 'A10', 'A11'],
                    'B': ['B8', 'B9', 'B10', 'B11'],
                    'C': ['C8', 'C9', 'C10', 'C11'],
                    'D': ['D8', 'D9', 'D10', 'D11']},
                   index=[8, 9, 10, 11])

In [ ]:
# 48 Page
# concat을 이용한 df1,df2,df3 결합,  axis 생략시 기본값: 세로 결합
result = pd.concat([df1, df2, df3])
# concat 결과 데이터 result 확인
result

In [ ]:
# 49 Page
# axis = 1: 세로 결합이 아닌 가로 결합
result = pd.concat([df1, df2, df3], axis = 1)
# concat 결과 데이터 result 확인
result

In [ ]:
# ignore_index = True: 기존 index가 아닌 새로운 index로 재생성
result = pd.concat([df1, df2, df3], axis = 1, ignore_index=True)
result

In [ ]:
# 컬럼명 추가
# concat 결과 데이터의 변수명 생성
result.columns = ["col_" + str(i) for i in range(12)]
# concat 결과 데이터 result 확인
result

### 데이터 결합 (MERGE)

DataFrame의 공통 열(column) 혹은 인덱스(index)를 기준으로 두 개의 DataFrame을 합침(변수 증가).
이 때 기준이 되는 열, 행을 키(key)라고 함

In [ ]:
# 55 Page (데이터결합 연습)
# left, right 데이터 생성
left = pd.DataFrame({'key1': ['K0', 'K1', 'K2', 'K3'],
                     'key2': ['K0', 'K1', 'K0', 'K1'],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
right = pd.DataFrame({'key1': ['K0', 'K1', 'K2', 'K3'],
                      'key2': ['K0', 'K0', 'K0', 'K0'],
                      'C': ['C0', 'C1', 'C2', 'C3'],
                      'D': ['D0', 'D1', 'D2', 'D3']})

In [ ]:
# merge 결과 result 생성
# 옵션 없음 : 기본값 : inner (교집합)
result = pd.merge(left, right, on=['key1','key2'])
result

In [ ]:
# 56 Page
# how = left
# left outer join
result = pd.merge(left, right, on=['key1','key2'], how='left')
result

In [ ]:
# how = right
# right outer join
result = pd.merge(left, right, on=['key1','key2'], how='right')
result

In [ ]:
# 57 Page
# how = outer
# full outer join : 합집합
result = pd.merge(left, right, on=['key1','key2'], how='outer')
result

In [ ]:
# indicator : merge 컬럼 생성 : 어느 데이터쪽에서 왔습니다.
result = pd.merge(left, right, on=['key1','key2'], how='outer', indicator=True)
result

#### merge와 join의 결정적 차이 
- pd.merge: 특정 컬럼(열)의 값을 기준으로 합칩니다. (예: 'ID'라는 칸의 값이 같은지 확인)

- df.join: 기본적으로 인덱스(Index, 행 번호/이름)를 기준으로 합칩니다.

### 데이터 결합 (JOIN)

조인은 인덱스를 기준으로 합친다.

In [ ]:
# 59 Page (데이터결합 연습)
# left, right 데이터 생성
left = pd.DataFrame({'key1': [1, 2, 3, 4],
                     'A': ['A0', 'A1', 'A2', 'A3'],
                     'B': ['B0', 'B1', 'B2', 'B3']})
right = pd.DataFrame({'C': ['C1', 'C2', 'C5'],
                      'D': ['D1', 'D2', 'D5']},
                     index=[1, 2, 5])

In [ ]:
# join 결과 result 생성
result = left.join(right)
result

In [ ]:
# 60 Page
# how = right 옵션을 넣어야 right outer join
result = left.join(right, how='right')
result

In [ ]:
# how = inner : 교집합 innder join
result = left.join(right, how='inner')
result

In [ ]:
# 61 Page
# how = outer
result = left.join(right, how='outer')
result

In [ ]:
# on: join의 key를 지정(left의 column명)
result = left.join(right, on='key1')
result

In [ ]:
# 62 Page
# join으로 결합
result = left.join(right, on='key1')
result

In [ ]:
# merge로 결합
result2 = pd.merge(left, right, left_on='key1', right_index=True, how='left');
result2

### 데이터 변환 (PIVOT)

In [31]:
# 69 Page (데이터변환 연습)
# df 데이터 생성
df = pd.DataFrame({'index': [1,1,1,2,2,2],
                   'column': ['col_1', 'col_2', 'col_3', 'col_1', 'col_2', 'col_3'],
                   'value_1': [1, 2, 3, 4, 5, 6],
                   'value_2': ['x', 'y', 'z', 'q', 'w', 't']})
df

   index column  value_1 value_2
0      1  col_1        1       x
1      1  col_2        2       y
2      1  col_3        3       z
3      2  col_1        4       q
4      2  col_2        5       w
5      2  col_3        6       t

In [32]:
# pivot: index, column, values를 지정하여 pivot
df.pivot(index='index', columns='column', values='value_1')

column  col_1  col_2  col_3
index
1           1      2      3
2           4      5      6

1. 피벗은 "자리 배치" 게임입니다
코드를 보면 3개의 인자를 정해줬죠? 이게 각각 어떤 자리에 갈지 결정한 거예요.

- index='index': "왼쪽 줄 번호는 원래 index 열에 있던 1, 2를 쓸게."

- columns='column': "위에 들어갈 제목은 column 열에 있던 col_1, col_2, col_3을 쓸게."

- values='value_1': "그 안을 채울 알맹이는 value_1에 있던 숫자들을 쓸게."

In [35]:
# 동일한 기능 다른 표현
df.pivot(index='index', columns='column')['value_2']

column col_1 col_2 col_3
index
1          x     y     z
2          q     w     t

In [36]:
# 70 Page
# 복수의 pivot column 지정
df.pivot(index='index', columns='column', values=['value_1','value_2'])

       value_1             value_2
column   col_1 col_2 col_3   col_1 col_2 col_3
index
1            1     2     3       x     y     z
2            4     5     6       q     w     t

In [37]:
# pivot column 미지정
df.pivot(index='index', columns='column')

       value_1             value_2
column   col_1 col_2 col_3   col_1 col_2 col_3
index
1            1     2     3       x     y     z
2            4     5     6       q     w     t

In [38]:
# index 미지정 시 변환되는 데이터 구조 주의 
df.pivot(columns='column', values='value_1')

column  col_1  col_2  col_3
0         1.0    NaN    NaN
1         NaN    2.0    NaN
2         NaN    NaN    3.0
3         4.0    NaN    NaN
4         NaN    5.0    NaN
5         NaN    NaN    6.0

### 데이터 변환 (MELT)

In [39]:
# 71 Page
# melt: id_vars를 제외한 나머지 컬럼을 풀어서 쌓음
df.melt(id_vars=['index','column'])

    index column variable value
0       1  col_1  value_1     1
1       1  col_2  value_1     2
2       1  col_3  value_1     3
3       2  col_1  value_1     4
4       2  col_2  value_1     5
5       2  col_3  value_1     6
6       1  col_1  value_2     x
7       1  col_2  value_2     y
8       1  col_3  value_2     z
9       2  col_1  value_2     q
10      2  col_2  value_2     w
11      2  col_3  value_2     t

In [ ]:
# 위에는 이름을 생략했당
df.melt(id_vars=['index','column'], 
        var_name='종류',    # variable 대신 들어갈 이름
        value_name='점수')  # value 대신 들어갈 이름

    index column       종류 점수
0       1  col_1  value_1  1
1       1  col_2  value_1  2
2       1  col_3  value_1  3
3       2  col_1  value_1  4
4       2  col_2  value_1  5
5       2  col_3  value_1  6
6       1  col_1  value_2  x
7       1  col_2  value_2  y
8       1  col_3  value_2  z
9       2  col_1  value_2  q
10      2  col_2  value_2  w
11      2  col_3  value_2  t

In [40]:
# id 및 value 컬럼 지정
df.melt(id_vars=['index','column'], value_vars=['value_1'])

   index column variable  value
0      1  col_1  value_1      1
1      1  col_2  value_1      2
2      1  col_3  value_1      3
3      2  col_1  value_1      4
4      2  col_2  value_1      5
5      2  col_3  value_1      6

### 데이터 변환 (stack/unstack)

데이터를 '위에서 아래로 차곡차곡 쌓는 것'  

가로로 펼쳐져 있는 '컬럼(열) 제목'을 90도 꺾어서, 세로 '인덱스(행)'로 쌓아 올리는 작업

In [42]:
# 76 Page (데이터변환 연습)
# df 데이터 생성
df = pd.DataFrame({'index': [1,2,3],
                   'alpha': ['A', 'B', 'C'],
                   'values': [11, 22, 33],
                   'xyz': ['x', 'y', 'z']})
df

   index alpha  values xyz
0      1     A      11   x
1      2     B      22   y
2      3     C      33   z

In [43]:
# index를 기준으로 변수들을 변환
df_stack = df.stack()
# 변환 결과 확인
print("stack 데이터 크기: ", df_stack.shape) # (12,) 배열
df_stack

stack 데이터 크기:  (12,)

0  index      1
   alpha      A
   values    11
   xyz        x
1  index      2
   alpha      B
   values    22
   xyz        y
2  index      3
   alpha      C
   values    33
   xyz        z
dtype: object

In [45]:
# 77 Page
# stack된 데이터를 원래의 형태로 변환
df_unstack = df_stack.unstack()
df_unstack

  index alpha values xyz
0     1     A     11   x
1     2     B     22   y
2     3     C     33   z

### 데이터 변환 (CROSSTAB)

In [46]:
# 81 Page (데이터변환 연습)
# df 데이터 생성
df = pd.DataFrame({'factor1': ['A', 'A', 'A', 'A', 'A','B','B','B', 'B'],
                   'factor2':['a','b','c','a','b','a','b', 'c','c'],
                   'value':[11,13,12,12,14,12,13,11,12]})
df

  factor1 factor2  value
0       A       a     11
1       A       b     13
2       A       c     12
3       A       a     12
4       A       b     14
5       B       a     12
6       B       b     13
7       B       c     11
8       B       c     12

In [ ]:
# index, columns 지정
pd.crosstab(df.factor1, df.factor2)

factor2  a  b  c
factor1
A        2  2  1
B        1  1  2

행(index)에는 factor1(A, B)을 두어라!

열(columns)에는 factor2(a, b, c)를 두어라!

동작: "A이면서 a인 애가 몇 명이지? B이면서 c인 애는 몇 명이지?"를 전수조사해서 개수를 세라!

factor1과 factor2의 항목들이 서로 교차하는 지점의 데이터 개수(빈도)를 집계  

별도 설정이 없으면 단순히 '건수'만 계산함

In [49]:
# 행/열 명칭 부여 및 margin 추가
pd.crosstab(df.factor1, df.factor2, 
            rownames=['Fact1'],colnames=['Fact2'],
            margins=True)

Fact2  a  b  c  All
Fact1
A      2  2  1    5
B      1  1  2    4
All    3  3  3    9

In [50]:
# 82 Page
# index-1개, columns-복수 개 컬럼 지정 가능
pd.crosstab(df.factor1, [df.factor2, df.value])

factor2  a     b     c
value   11 12 13 14 11 12
factor1
A        1  1  1  1  0  1
B        0  1  1  0  1  1

In [51]:
# 각 셀의 빈도 기준 정규화 확률 산출
pd.crosstab(df.factor1, df.factor2, margins=True, 
            normalize=True)

factor2         a         b         c       All
factor1
A        0.222222  0.222222  0.111111  0.555556
B        0.111111  0.111111  0.222222  0.444444
All      0.333333  0.333333  0.333333  1.000000

normalize: "개수(Count)"를 "비중(Percentage)"으로 바꿔주는 마법의 옵션

### 데이터 변환 (SORT)

In [52]:
# 85 Page (데이터변환 연습)
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9], 'c3':[10,11,12], 'c4':[13,14,15]}
df = pd.DataFrame(dict_data, index=['r0', 'r1', 'r2'])
df

    c0  c1  c2  c3  c4
r0   1   4   7  10  13
r1   2   5   8  11  14
r2   3   6   9  12  15

In [53]:
df_sort = df.sort_index(ascending=False)
df_sort

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

In [54]:
df_sort = df.sort_values(by='c1', ascending=False)
df_sort

    c0  c1  c2  c3  c4
r2   3   6   9  12  15
r1   2   5   8  11  14
r0   1   4   7  10  13

### 데이터 중복 확인

In [ ]:
# 88 Page (데이터중복확인 연습)
# 데이터 불러오기
df = pd.read_excel(r'D:\BigData_수업용\2605619_33기 AI·Big Data 실습 파일, 연습 코드\1. Big Data 분석 기초 실습파일\판매실적_이해.xlsx', sheet_name = 'Sheet1')
df = df.dropna()
df.head()

   지역   제품  판매수   판매액
0  동부   TV    1  1000
1  남부   TV    1  1000
2  서부  냉장고    1  2000
3  동부  세탁기    1  1000
4  북부  세탁기    1  1000

In [57]:
# 중복 데이터 조회(Boolean)
df.duplicated()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8      True
9      True
10    False
11    False
dtype: bool

In [58]:
# 중복 데이터 조회
df[df.duplicated()]

   지역   제품  판매수   판매액
8  동부   TV    1  1000
9  남부  냉장고    1  2000

In [59]:
# 중복 데이터 제거 
df.drop_duplicates(ignore_index=True)

   지역   제품  판매수   판매액
0  동부   TV    1  1000
1  남부   TV    1  1000
2  서부  냉장고    1  2000
3  동부  세탁기    1  1000
4  북부  세탁기    1  1000
5  동부  냉장고    2  4000
6  남부  냉장고    1  2000
7  서부  세탁기    1  1000
8  서부   TV    1  1000
9  남부  세탁기    1  1000

In [60]:
# 중복 데이터 조회
df[df.duplicated()]

   지역   제품  판매수   판매액
8  동부   TV    1  1000
9  남부  냉장고    1  2000

In [61]:
# 중복 데이터 제거 
df.drop_duplicates(ignore_index=True)

   지역   제품  판매수   판매액
0  동부   TV    1  1000
1  남부   TV    1  1000
2  서부  냉장고    1  2000
3  동부  세탁기    1  1000
4  북부  세탁기    1  1000
5  동부  냉장고    2  4000
6  남부  냉장고    1  2000
7  서부  세탁기    1  1000
8  서부   TV    1  1000
9  남부  세탁기    1  1000

In [62]:
# 91 Page
import pandas as pd
import numpy as np
# data = pd.read_csv('파일경로', sep = "\t", , engine='python', encoding = "인코딩방식")
pop_seoul = pd.read_csv(r'D:\BigData_수업용\2605619_33기 AI·Big Data 실습 파일, 연습 코드\1. Big Data 분석 기초 실습파일\서울인구통계.txt',sep="\t", thousands = ',',
                        skiprows = 2, encoding = "utf-8")
pop_seoul.head()

,기간,자치구,세대,계,남자,여자,계.1,남자.1,여자.1,계.2,남자.2,여자.2,세대당인구,65세이상고령자
0,2021.3/4,합계,4421143,9765869,4739972,5025897,9542256,4636069,4906187,223613,103903,119710,2.16,1592339
1,2021.3/4,종로구,73652,154318,74561,79757,145512,70666,74846,8806,3895,4911,1.98,27776
2,2021.3/4,중구,63267,131943,64274,67669,122858,59853,63005,9085,4421,4664,1.94,24225
3,2021.3/4,용산구,111177,238300,115655,122645,224145,107801,116344,14155,7854,6301,2.02,38906
4,2021.3/4,성동구,134620,294140,143055,151085,287820,140290,147530,6320,2765,3555,2.14,46053

In [ ]:
# 92 Page
# 자치구별 인구합계, 한국인 합계, 외국인 합계, 고령자 데이터만을 추출
# index 0,1행은 중복으로 필요 없는 행으로 삭제
pop1 = pop_seoul[['자치구', '계', '계.1', '계.2', '65세이상고령자']]
pop_seoul= pop1.drop([0])   
pop_seoul.head()

   자치구       계     계.1    계.2  65세이상고령자
1  종로구  154318  145512   8806     27776
2   중구  131943  122858   9085     24225
3  용산구  238300  224145  14155     38906
4  성동구  294140  287820   6320     46053
5  광진구  353380  341112  12268     51278

In [64]:
# 컬럼명을 구분할 수 있도록 리네임
pop_seoul.rename(columns={pop_seoul.columns[0]: '구별', 
                          pop_seoul.columns[1]: '인구수', 
                          pop_seoul.columns[2]: '한국인', 
                          pop_seoul.columns[3]: '외국인', 
                          pop_seoul.columns[4]: '고령자' 
                          }, inplace=True)
pop_seoul.head()

    구별     인구수     한국인    외국인    고령자
1  종로구  154318  145512   8806  27776
2   중구  131943  122858   9085  24225
3  용산구  238300  224145  14155  38906
4  성동구  294140  287820   6320  46053
5  광진구  353380  341112  12268  51278

In [66]:
# 93 Page
cctv_seoul=pd.read_excel(r'D:\BigData_수업용\2605619_33기 AI·Big Data 실습 파일, 연습 코드\1. Big Data 분석 기초 실습파일\서울시CCTV.xlsx', skiprows = 2, 
                        names = ['기관명', '소계', '2011년 이전', '2012년', '2013년', '2014년', '2015년', 
                                 '2016년', '2017년', '2018년', '2019년', '2020년', '2021년'])
cctv_seoul.head()

,기관명,소계,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,종로구,1772,813,0,0,210,150,1,261,85,9,200,43
1,중 구,2333,16,114,87,77,236,240,372,386,155,361,289
2,용산구,2383,34,71,234,125,221,298,351,125,307,617,0
3,성동구,3602,448,125,212,105,339,310,874,390,262,461,76
4,광진구,2588,35,57,100,187,98,52,675,465,712,175,32

In [67]:
cctv_seoul.columns

Index(['기관명', '소계', '2011년 이전', '2012년', '2013년', '2014년', '2015년', '2016년',
       '2017년', '2018년', '2019년', '2020년', '2021년'],
      dtype='object')

In [ ]:
# 94 Page
# 인구통계 자료와 통일을 하기 위해 기관명을 구별로 인덱스 이름 변경
cctv_seoul.rename(columns={cctv_seoul.columns[0] : '구별'},inplace=True)
# inplace=TRUE로 해야지 값까지 다 포함해서 가져감
cctv_seoul.rename(columns={cctv_seoul.columns[1] : 'cctv수'},inplace=True) 
# 소계를 cctv수로 이름 변경
cctv_seoul.head()

,구별,cctv수,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
0,종로구,1772,813,0,0,210,150,1,261,85,9,200,43
1,중 구,2333,16,114,87,77,236,240,372,386,155,361,289
2,용산구,2383,34,71,234,125,221,298,351,125,307,617,0
3,성동구,3602,448,125,212,105,339,310,874,390,262,461,76
4,광진구,2588,35,57,100,187,98,52,675,465,712,175,32

In [69]:
# 95 Page
# sort_values : 값을 기준으로 정렬, by=기준 열
cctv_seoul.sort_values(by='cctv수',ascending=True).head(10)  #True 오름차순

,구별,cctv수,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
9,도봉구,1629,39,22,96,181,79,159,134,222,198,168,331
0,종로구,1772,813,0,0,210,150,1,261,85,9,200,43
19,동작구,2297,41,24,25,503,128,253,271,300,322,419,11
1,중 구,2333,16,114,87,77,236,240,372,386,155,361,289
17,금천구,2374,0,0,178,80,361,133,196,540,369,508,9
2,용산구,2383,34,71,234,125,221,298,351,125,307,617,0
10,노원구,2415,0,97,193,77,516,331,175,216,320,386,104
13,마포구,2421,58,93,77,61,162,454,359,343,494,300,20
8,강북구,2462,0,0,24,65,105,243,6,392,1000,588,39
5,동대문구,2497,1090,146,60,29,111,233,136,197,209,223,63

In [70]:
cctv_seoul.sort_values(by='cctv수',ascending=False).head(10) #False 내림차순

,구별,cctv수,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년
22,강남구,6502,124,77,75,597,840,1310,999,748,789,942,1
20,관악구,4942,428,205,291,513,529,621,687,663,640,331,34
16,구로구,4075,852,216,349,187,268,326,540,488,434,415,0
7,성북구,3958,83,78,170,230,323,594,460,867,714,251,188
11,은평구,3791,14,3,44,332,329,555,403,635,1057,288,131
18,영등포구,3778,572,136,238,123,209,248,311,658,65,1213,5
21,서초구,3704,116,75,94,71,563,516,1060,428,358,420,3
3,성동구,3602,448,125,212,105,339,310,874,390,262,461,76
14,양천구,3312,1413,167,181,143,180,350,139,140,274,325,0
6,중랑구,3296,302,24,253,88,141,161,162,173,1049,939,4

In [ ]:
# 96 Page
cctv_seoul.isnull().sum()

구별          0
cctv수       0
2011년 이전    0
2012년       0
2013년       0
2014년       0
2015년       0
2016년       0
2017년       0
2018년       0
2019년       0
2020년       0
2021년       0
dtype: int64

In [72]:
# 97 Page
# 최근 3년간 cctv 증가율 비교
# 증가율 = 2019~2021 cctv 수/2019년 이전 cctv 수
cctv_seoul['최근증가율']=(cctv_seoul['2021년']+cctv_seoul['2020년']+cctv_seoul['2019년']) \
   /(cctv_seoul['cctv수']-(cctv_seoul['2021년']+cctv_seoul['2020년']+cctv_seoul['2019년']))*100
cctv_seoul.sort_values(by='최근증가율',ascending=False).head(5)

,구별,cctv수,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,최근증가율
8,강북구,2462,0,0,24,65,105,243,6,392,1000,588,39,194.850299
6,중랑구,3296,302,24,253,88,141,161,162,173,1049,939,4,152.760736
23,송파구,2854,72,61,86,85,215,148,241,542,1068,235,101,96.827586
9,도봉구,1629,39,22,96,181,79,159,134,222,198,168,331,74.785408
11,은평구,3791,14,3,44,332,329,555,403,635,1057,288,131,63.758099

In [74]:
# 98 Page
# 구별 ‘외국인비율＇과 ‘고령자비율＇을 계산
pop_seoul['외국인 비율']=pop_seoul['외국인']/pop_seoul['인구수']*100
pop_seoul['고령자 비율']=pop_seoul['고령자']/pop_seoul['인구수']*100
pop_seoul.head()

    구별     인구수     한국인    외국인    고령자    외국인 비율     고령자 비율
1  종로구  154318  145512   8806  27776  5.706398  17.999196
2   중구  131943  122858   9085  24225  6.885549  18.360201
3  용산구  238300  224145  14155  38906  5.939992  16.326479
4  성동구  294140  287820   6320  46053  2.148637  15.656830
5  광진구  353380  341112  12268  51278  3.471617  14.510725

In [75]:
# 99 Page
# 전체 ‘외국인비율'로 정렬
pop_seoul.sort_values(by='외국인 비율', ascending=False).head()

      구별     인구수     한국인    외국인    고령자    외국인 비율     고령자 비율
2     중구  131943  122858   9085  24225  6.885549  18.360201
19  영등포구  401814  377536  24278  62108  6.042099  15.456903
3    용산구  238300  224145  14155  38906  5.939992  16.326479
17   구로구  422361  397506  24855  71930  5.884776  17.030455
18   금천구  244887  230644  14243  40691  5.816152  16.616235

In [76]:
pop_seoul.sort_values(by='고령자 비율', ascending=False).head()

     구별     인구수     한국인   외국인    고령자    외국인 비율     고령자 비율
9   강북구  304257  300887  3370  63914  1.107616  21.006583
10  도봉구  320711  318718  1993  63448  0.621432  19.783543
2    중구  131943  122858  9085  24225  6.885549  18.360201
12  은평구  477961  474062  3899  86724  0.815757  18.144577
7   중랑구  393149  388554  4595  70908  1.168768  18.035910

In [77]:
cctv_seoul

,구별,cctv수,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,최근증가율
0,종로구,1772,813,0,0,210,150,1,261,85,9,200,43,16.578947
1,중 구,2333,16,114,87,77,236,240,372,386,155,361,289,52.683246
2,용산구,2383,34,71,234,125,221,298,351,125,307,617,0,63.331049
3,성동구,3602,448,125,212,105,339,310,874,390,262,461,76,28.505173
4,광진구,2588,35,57,100,187,98,52,675,465,712,175,32,55.062912
5,동대문구,2497,1090,146,60,29,111,233,136,197,209,223,63,24.725275
6,중랑구,3296,302,24,253,88,141,161,162,173,1049,939,4,152.760736
7,성북구,3958,83,78,170,230,323,594,460,867,714,251,188,41.105169
8,강북구,2462,0,0,24,65,105,243,6,392,1000,588,39,194.850299
9,도봉구,1629,39,22,96,181,79,159,134,222,198,168,331,74.785408
10,노원구,2415,0,97,193,77,516,331,175,216,320,386,104,50.467290
11,은평구,3791,14,3,44,332,329,555,403,635,1057,288,131,63.758099
12,서대문구,2940,730,253,155,108,137,223,356,237,343,397,1,33.697135
13,마포구,2421,58,93,77,61,162,454,359,343,494,300,20,50.653391
14,양천구,3312,1413,167,181,143,180,350,139,140,274,325,0,22.078879
15,강서구,2560,55,129,106,213,188,168,506,259,457,356,123,57.635468
16,구로구,4075,852,216,349,187,268,326,540,488,434,415,0,26.317421
17,금천구,2374,0,0,178,80,361,133,196,540,369,508,9,59.543011
18,영등포구,3778,572,136,238,123,209,248,311,658,65,1213,5,51.422846
19,동작구,2297,41,24,25,503,128,253,271,300,322,419,11,48.673139
20,관악구,4942,428,205,291,513,529,621,687,663,640,331,34,25.527051
21,서초구,3704,116,75,94,71,563,516,1060,428,358,420,3,26.719124
22,강남구,6502,124,77,75,597,840,1310,999,748,789,942,1,36.310273
23,송파구,2854,72,61,86,85,215,148,241,542,1068,235,101,96.827586
24,강동구,2547,332,27,163,49,154,202,273,377,356,614,0,61.509195

In [78]:
# 100 Page
# cctv_seoul의 “구별” 열의 내용이 글자사이 공백으로 인해 병합이 되지 않기 때문에 rename 실시
# cctv_seoul['구별']=['종로구','중구','용산구','성동구','광진구','동대문구','중랑구','성북구','강북구','도봉구',
#                  '노원구','은평구','서대문구','마포구','양천구','강서구','구로구','금천구','영등포구','동작구',
#                  '관악구','서초구','강남구','송파구','강동구']
        
cctv_seoul['구별'] = cctv_seoul['구별'].str.replace(' ','')

In [79]:
# merge를 사용하여 병합
result = pd.merge(cctv_seoul, pop_seoul, on='구별')
result.head()

,구별,cctv수,2011년 이전,2012년,2013년,2014년,2015년,2016년,2017년,2018년,2019년,2020년,2021년,최근증가율,인구수,한국인,외국인,고령자,외국인 비율,고령자 비율
0,종로구,1772,813,0,0,210,150,1,261,85,9,200,43,16.578947,154318,145512,8806,27776,5.706398,17.999196
1,중구,2333,16,114,87,77,236,240,372,386,155,361,289,52.683246,131943,122858,9085,24225,6.885549,18.360201
2,용산구,2383,34,71,234,125,221,298,351,125,307,617,0,63.331049,238300,224145,14155,38906,5.939992,16.326479
3,성동구,3602,448,125,212,105,339,310,874,390,262,461,76,28.505173,294140,287820,6320,46053,2.148637,15.656830
4,광진구,2588,35,57,100,187,98,52,675,465,712,175,32,55.062912,353380,341112,12268,51278,3.471617,14.510725