## 과제

### 실습 1:  pandas 패키지를 이용하여 Series구조와 DataFrame구조의 데이터를 생성해보시오.

#### STEP ❶ : Series 구조 데이터 생성하기

In [2]:
import pandas as pd 

# Series 구조생성
name = { 1 : "홍길동", 2 : "이순신", 3 : "강감찬"}
sr = pd.Series(name)
print(type(sr))
print(sr)

<class 'pandas.core.series.Series'>
1    홍길동
2    이순신
3    강감찬
dtype: object

####   STEP ❷ : DataFrame 구조 데이터 생성하기

In [3]:
# DataFrame 구조생성
table = {"성명" : ['홍길동', '이순신', '강감찬', '이성계', '정약용'],
        "국어성적" : [90, 95, 85, 90, 95],
        "영어성적" : [90, 85, 90, 95, 95],
        "수학성적" :  [95, 90, 85, 75, 90]}
df = pd.DataFrame(table)
df

    성명  국어성적  영어성적  수학성적
0  홍길동    90    90    95
1  이순신    95    85    90
2  강감찬    85    90    85
3  이성계    90    95    75
4  정약용    95    95    90

### 실습 2: pandas 패키지를 이용하여 데이터 읽어오기와 파일 저장하기를 실습하시오.

#### STEP ❶ : 데이터 파일 읽어오기

In [4]:
# r (Raw String) 사용; 윈도우 환경에서 실행 중임
df = pd.read_csv(r"D:\BigData_수업용\2605619_33기 AI·Big Data 실습 파일, 연습 코드\1. Big Data 분석 기초 실습파일\성적.csv", encoding = 'euc-kr')
df.head()

   Unnamed: 0   성명  국어성적  영어성적  수학성적
0           0  홍길동    90    90    95
1           1  이순신    95    85    90
2           2  강감찬    85    90    85
3           3  이성계    90    95    75
4           4  정약용    95    95    90

#### STEP ❷ : DataFrame 구조 데이터 생성 및 파일로 저장하기

In [5]:
table = {"성명" : ['홍길동', '이순신', '강감찬', '이성계', '정약용'],
        "국어성적" : [90, 95, 85, 90, 95],
        "영어성적" : [90, 85, 90, 95, 95],
        "수학성적" :  [95, 90, 85, 75, 90]}
df = pd.DataFrame(table)
df

    성명  국어성적  영어성적  수학성적
0  홍길동    90    90    95
1  이순신    95    85    90
2  강감찬    85    90    85
3  이성계    90    95    75
4  정약용    95    95    90

In [6]:
df.to_csv(r"C:\Users\User\Desktop\data\연습코드.csv", encoding='euc-kr', index=False)

df.to_excel(r"C:\Users\User\Desktop\data\연습코드.xlsx", index=False)

### 실습 3: 데이터를 읽어와서 데이터의 내용을 확인절차에 맞추어 진행하시오.

#### STEP ❶ : 데이터 읽어오기

In [7]:
df = pd.read_csv(r"D:\BigData_수업용\2605619_33기 AI·Big Data 실습 파일, 연습 코드\1. Big Data 분석 기초 실습파일\FITNESS.csv", encoding = 'euc-kr')

#### STEP ❷ : 데이터의 내용 미리보기

In [8]:
df.head()

,NAME,GENDER,AGE,AGEGROUP,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
0,Donna,여성,42,40대,68.15,59.571,8.17,166,40,172
1,Gracie,여성,38,30대,81.87,60.055,8.63,170,48,186
2,Luanne,여성,43,40대,85.84,54.297,8.65,156,45,168
3,Mimi,여성,50,50대,70.87,54.625,8.92,146,48,155
4,Chris,남성,49,40대,81.42,49.156,8.95,180,44,185

In [9]:
df.tail()

,NAME,GENDER,AGE,AGEGROUP,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
26,Iris,여성,39,30대,75.98,45.681,11.95,176,70,180
27,Mark,남성,57,50대,73.37,39.407,12.63,174,58,176
28,Steve,남성,54,50대,91.63,39.203,12.88,168,44,172
29,Vaughn,남성,44,40대,81.42,39.442,13.08,174,63,176
30,William,남성,45,40대,87.66,37.388,14.03,186,56,192

#### STEP ❸ : 요약정보 확인하기

In [10]:
df.shape

(31, 10)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 31 entries, 0 to 30
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   NAME      31 non-null     object
 1   GENDER    31 non-null     object
 2   AGE       31 non-null     int64
 3   AGEGROUP  31 non-null     object
 4   WEIGHT    31 non-null     float64
 5   OXY       31 non-null     float64
 6   RUNTIME   31 non-null     float64
 7   RUNPULSE  31 non-null     int64
 8   RSTPULSE  31 non-null     int64
 9   MAXPULSE  31 non-null     int64
dtypes: float64(3), int64(4), object(3)
memory usage: 2.6+ KB

In [12]:
df.dtypes

NAME         object
GENDER       object
AGE           int64
AGEGROUP     object
WEIGHT      float64
OXY         float64
RUNTIME     float64
RUNPULSE      int64
RSTPULSE      int64
MAXPULSE      int64
dtype: object

In [13]:
df.OXY.dtypes

dtype('float64')

In [14]:
df.describe()

,AGE,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
count,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
mean,46.838710,77.444516,47.375806,10.586129,169.645161,53.451613,173.774194
std,5.860016,8.328568,5.327231,1.387414,10.251986,7.619443,9.164095
min,37.000000,59.080000,37.388000,8.170000,146.000000,40.000000,155.000000
25%,43.000000,73.200000,44.964500,9.780000,163.000000,48.000000,168.000000
50%,48.000000,77.450000,46.774000,10.470000,170.000000,52.000000,172.000000
75%,51.000000,82.325000,50.131000,11.270000,176.000000,58.500000,180.000000
max,57.000000,91.630000,60.055000,14.030000,186.000000,70.000000,192.000000

In [15]:
df.describe(include="all")

,NAME,GENDER,AGE,AGEGROUP,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
count,31,31,31.000000,31,31.000000,31.000000,31.000000,31.000000,31.000000,31.000000
unique,31,2,NaN,3,NaN,NaN,NaN,NaN,NaN,NaN
top,Donna,여성,NaN,40대,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,16,NaN,14,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,46.838710,NaN,77.444516,47.375806,10.586129,169.645161,53.451613,173.774194
std,NaN,NaN,5.860016,NaN,8.328568,5.327231,1.387414,10.251986,7.619443,9.164095
min,NaN,NaN,37.000000,NaN,59.080000,37.388000,8.170000,146.000000,40.000000,155.000000
25%,NaN,NaN,43.000000,NaN,73.200000,44.964500,9.780000,163.000000,48.000000,168.000000
50%,NaN,NaN,48.000000,NaN,77.450000,46.774000,10.470000,170.000000,52.000000,172.000000
75%,NaN,NaN,51.000000,NaN,82.325000,50.131000,11.270000,176.000000,58.500000,180.000000
max,NaN,NaN,57.000000,NaN,91.630000,60.055000,14.030000,186.000000,70.000000,192.000000

#### STEP ❹ : 데이터 개수 및 집계함수 활용

In [16]:
df.groupby(['GENDER'], as_index = False).mean(numeric_only=True)

# numeric_only=True 옵션 추가 : 데이터타입이 객체인 컬럼 존재 -> 계산 실패

,GENDER,AGE,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
0,남성,46.333333,82.282667,44.753733,11.19400,172.20,55.733333,175.800
1,여성,47.312500,72.908750,49.834000,10.01625,167.25,51.312500,171.875

In [17]:
#df.dtypes 결과에서 int형만 골라 평균치와 중앙값을 확인하도록 하겠습니다.
# NAME, GENDER, AGEGROUP 등 문자열(object) 컬럼은 제외함
# 1. 숫자 컬럼들만 리스트로 정의
numeric_cols = ['AGE', 'WEIGHT', 'OXY', 'RUNTIME', 'RUNPULSE', 'RSTPULSE', 'MAXPULSE']

# 2. GENDER로 그룹화한 뒤, 선택한 컬럼들에 대해 mean과 median 산출
result = df.groupby('GENDER')[numeric_cols].agg(['mean', 'median'])
result

              AGE            WEIGHT               OXY            RUNTIME  \
             mean median       mean median       mean   median      mean
GENDER
남성      46.333333   45.0  82.282667  81.42  44.753733  45.3130  11.19400
여성      47.312500   48.5  72.908750  73.54  49.834000  48.2965  10.01625

              RUNPULSE          RSTPULSE        MAXPULSE
       median     mean median       mean median     mean median
GENDER
남성      10.95   172.20  174.0  55.733333   57.0  175.800  176.0
여성      10.04   167.25  168.0  51.312500   48.0  171.875  170.0

### 실습 4. 정규분포에서 추출한 10개의 무작위 데이터로 slice, loc, iloc, query 등을 이용하여 데이터를 선택하라.

#### STEP ❶ : 데이터 구성하기

In [18]:
import pandas as pd
import numpy as np
from numpy.random import randn

# random seed = 1234
np.random.seed(1234)

# 변수: 4개, 자료 수: 10개
df = pd.DataFrame(randn(10, 4), columns = ['A', 'B', 'C', 'D'])
df

          A         B         C         D
0  0.471435 -1.190976  1.432707 -0.312652
1 -0.720589  0.887163  0.859588 -0.636524
2  0.015696 -2.242685  1.150036  0.991946
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092
9  0.124713 -0.322795  0.841675  2.390961

#### STEP ❷ : slice

In [19]:
# B열 선택
df['B']

0   -1.190976
1    0.887163
2   -2.242685
3   -2.021255
4    0.289092
5   -0.655969
6   -0.469305
7    1.058969
8    1.045938
9   -0.322795
Name: B, dtype: float64

In [20]:
# B,D열 선택
df[['B', 'D']]

          B         D
0 -1.190976 -0.312652
1  0.887163 -0.636524
2 -2.242685  0.991946
3 -2.021255  0.002118
4  0.289092 -1.546906
5 -0.655969  0.553439
6 -0.469305 -1.817027
7  1.058969  0.337438
8  1.045938 -0.122092
9 -0.322795  2.390961

In [21]:
# 4~8행 선택
df[4:9]

          A         B         C         D
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092

#### STEP ❸ : loc / iloc

In [22]:
# 2~8행, A,C열 선택
df.loc[2:8,['A', 'C']]

          A         C
2  0.015696  1.150036
3  0.953324 -0.334077
4  0.405453  1.321158
5 -0.202646  0.193421
6  1.318152  0.675554
7 -0.183109 -0.397840
8  1.047579  0.863717

In [23]:
# A,C열 선택
df.loc[:, ['A', 'C']]

          A         C
0  0.471435  1.432707
1 -0.720589  0.859588
2  0.015696  1.150036
3  0.953324 -0.334077
4  0.405453  1.321158
5 -0.202646  0.193421
6  1.318152  0.675554
7 -0.183109 -0.397840
8  1.047579  0.863717
9  0.124713  0.841675

In [24]:
# 3~8행 선택
df.loc[3:8]

          A         B         C         D
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092

In [25]:
# 3행 선택 (단일행)
df.loc[3:3]

          A         B         C         D
3  0.953324 -2.021255 -0.334077  0.002118

In [26]:
# 0~6행, A열 선택
df.iloc[0:7, [0]]

          A
0  0.471435
1 -0.720589
2  0.015696
3  0.953324
4  0.405453
5 -0.202646
6  1.318152

In [27]:
# A열 선택
df.iloc[:, [0]]

          A
0  0.471435
1 -0.720589
2  0.015696
3  0.953324
4  0.405453
5 -0.202646
6  1.318152
7 -0.183109
8  1.047579
9  0.124713

In [28]:
# 2~6행 선택
df.iloc[2:7]

          A         B         C         D
2  0.015696 -2.242685  1.150036  0.991946
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
5 -0.202646 -0.655969  0.193421  0.553439
6  1.318152 -0.469305  0.675554 -1.817027

In [29]:
# 5행 선택 (단일행)
df.iloc[5:6]

          A         B         C         D
5 -0.202646 -0.655969  0.193421  0.553439

#### STEP ❹ : query

In [30]:
# D > 0.5 데이터 선택
df.query('D > 0.5')

          A         B         C         D
2  0.015696 -2.242685  1.150036  0.991946
5 -0.202646 -0.655969  0.193421  0.553439
9  0.124713 -0.322795  0.841675  2.390961

In [31]:
# B>D 데이터 선택
df.query ('B > D')

          A         B         C         D
1 -0.720589  0.887163  0.859588 -0.636524
4  0.405453  0.289092  1.321158 -1.546906
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092

In [32]:
# B>D 데이터 선택 (slice 표현)
df[df.B>df.D]

          A         B         C         D
1 -0.720589  0.887163  0.859588 -0.636524
4  0.405453  0.289092  1.321158 -1.546906
6  1.318152 -0.469305  0.675554 -1.817027
7 -0.183109  1.058969 -0.397840  0.337438
8  1.047579  1.045938  0.863717 -0.122092

In [33]:
# A>0.5 그리고 D<0.0 데이터 선택
df.query ('A > 0.5 & D < 0.0')

          A         B         C         D
6  1.318152 -0.469305  0.675554 -1.817027
8  1.047579  1.045938  0.863717 -0.122092

In [34]:
# A>0.5 혹은 D<0.0 데이터 선택
df.query ('A > 0.5 | D < 0.0')

          A         B         C         D
0  0.471435 -1.190976  1.432707 -0.312652
1 -0.720589  0.887163  0.859588 -0.636524
3  0.953324 -2.021255 -0.334077  0.002118
4  0.405453  0.289092  1.321158 -1.546906
6  1.318152 -0.469305  0.675554 -1.817027
8  1.047579  1.045938  0.863717 -0.122092

### 실습 5: df4, df5, df6을 이용해 concat(좌우 결합)을 실행하라

#### STEP ❶ : 데이터 구성하기

In [35]:
# 데이터 구성하기
df4 = pd.DataFrame({'A': ['A0','A1','A2','A3'], 
                   'B':['B0','B1','B2','B3'],
                   'C':['C0','C1','C2','C3'],
                   'D':['D0','D1','D2','D3'], }, index=[0, 1, 2, 3])


df5 = pd.DataFrame({'E': ['E0','E1','E2','E3'], 
                   'F':['F0','F1','F2','F3'],
                   'G':['G0','G1','G2','G3'],
                   'H':['H0','H1','H2','H3'] }, index=[0, 1, 2, 3])


df6 = pd.DataFrame({'I': ['I0','I1','I2','I3'], 
                   'J':['J0','J1','J2','J3'],
                   'K':['K0','K1','K2','K3'],
                   'L':['L0','L1','L2','L3'] }, index=[0, 1, 2, 3])

#### STEP ❷ concat을 이용한 데이터 결합

In [36]:
result = pd.concat([df4, df5, df6])     #axis = 1 : 가로 결합

result

     A    B    C    D    E    F    G    H    I    J    K    L
0   A0   B0   C0   D0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
3   A3   B3   C3   D3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN   E0   F0   G0   H0  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN   E1   F1   G1   H1  NaN  NaN  NaN  NaN
2  NaN  NaN  NaN  NaN   E2   F2   G2   H2  NaN  NaN  NaN  NaN
3  NaN  NaN  NaN  NaN   E3   F3   G3   H3  NaN  NaN  NaN  NaN
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   I0   J0   K0   L0
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   I1   J1   K1   L1
2  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   I2   J2   K2   L2
3  NaN  NaN  NaN  NaN  NaN  NaN  NaN  NaN   I3   J3   K3   L3

#### STEP ❸ : parameter 변경

In [37]:
# 가로 결합
result = pd.concat([df4, df5, df6], axis = 1)    
result

    A   B   C   D   E   F   G   H   I   J   K   L
0  A0  B0  C0  D0  E0  F0  G0  H0  I0  J0  K0  L0
1  A1  B1  C1  D1  E1  F1  G1  H1  I1  J1  K1  L1
2  A2  B2  C2  D2  E2  F2  G2  H2  I2  J2  K2  L2
3  A3  B3  C3  D3  E3  F3  G3  H3  I3  J3  K3  L3

In [38]:
# 새로운 index 생성
result = pd.concat([df4, df5, df6], axis = 1, ignore_index=True)
result

   0   1   2   3   4   5   6   7   8   9   10  11
0  A0  B0  C0  D0  E0  F0  G0  H0  I0  J0  K0  L0
1  A1  B1  C1  D1  E1  F1  G1  H1  I1  J1  K1  L1
2  A2  B2  C2  D2  E2  F2  G2  H2  I2  J2  K2  L2
3  A3  B3  C3  D3  E3  F3  G3  H3  I3  J3  K3  L3

In [39]:
#변수명 생성
result.columns = ['col_'+ str(i) for i in range(12)]

result

  col_0 col_1 col_2 col_3 col_4 col_5 col_6 col_7 col_8 col_9 col_10 col_11
0    A0    B0    C0    D0    E0    F0    G0    H0    I0    J0     K0     L0
1    A1    B1    C1    D1    E1    F1    G1    H1    I1    J1     K1     L1
2    A2    B2    C2    D2    E2    F2    G2    H2    I2    J2     K2     L2
3    A3    B3    C3    D3    E3    F3    G3    H3    I3    J3     K3     L3

### 실습 6: merge를 이용해 FITNESS 데이터로 만들어라.

#### STEP ❶ : 데이터 구성하기

In [40]:
FITNESS_1 = pd.read_csv(r"D:\BigData_수업용\2605619_33기 AI·Big Data 실습 파일, 연습 코드\1. Big Data 분석 기초 실습파일\FITNESS_1.csv", encoding = 'euc-kr')
FITNESS_1.head(3)

     NAME GENDER  AGE AGEGROUP  WEIGHT
0   Donna     여성   42      40대   68.15
1  Gracie     여성   38      30대   81.87
2  Luanne     여성   43      40대   85.84

In [41]:
FITNESS_2 = pd.read_csv(r"D:\BigData_수업용\2605619_33기 AI·Big Data 실습 파일, 연습 코드\1. Big Data 분석 기초 실습파일\FITNESS_2.csv", encoding= 'euc-kr' )
FITNESS_2.head(3)

     NAME GENDER  AGE     OXY  RUNTIME  RUNPULSE  RSTPULSE  MAXPULSE
0   Donna     여성   42  59.571     8.17       166        40       172
1  Gracie     여성   38  60.055     8.63       170        48       186
2  Luanne     여성   43  54.297     8.65       156        45       168

#### STEP ❷ : merge를 이용한 결합

In [42]:
df_merged = pd.merge(FITNESS_1, FITNESS_2, on=['NAME', 'GENDER', 'AGE'])

df_merged.head(3)

,NAME,GENDER,AGE,AGEGROUP,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
0,Donna,여성,42,40대,68.15,59.571,8.17,166,40,172
1,Gracie,여성,38,30대,81.87,60.055,8.63,170,48,186
2,Luanne,여성,43,40대,85.84,54.297,8.65,156,45,168

#### STEP ❸ : 원본 FITNESS 데이터와 비교

In [43]:
fitness_merged = pd.merge(FITNESS_1, FITNESS_2, on='NAME')

fitness_merged.head(3)

,NAME,GENDER_x,AGE_x,AGEGROUP,WEIGHT,GENDER_y,AGE_y,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
0,Donna,여성,42,40대,68.15,여성,42,59.571,8.17,166,40,172
1,Gracie,여성,38,30대,81.87,여성,38,60.055,8.63,170,48,186
2,Luanne,여성,43,40대,85.84,여성,43,54.297,8.65,156,45,168

#### 비교
- on='NAME': NAME만 기준으로 합치니, 양쪽에 다 있는 GENDER, AGE 컬럼이 각각 _x, _y로 나뉘어 중복 생성됩니다.

- on=['NAME', 'GENDER', 'AGE']: 이름, 성별, 나이 3개를 모두 기준으로 합치니, 중복 없이 하나의 컬럼으로 깔끔하게 합쳐집니다.

### 실습 7:  pivot을 이용하여 GENDER와 AGEGROUP별 WEIGHT의 평균을 아래와 같이 변환하라.

#### STEP ❶ : 데이터 구성하기

In [44]:
FITNESS = pd.read_csv(r"D:\BigData_수업용\2605619_33기 AI·Big Data 실습 파일, 연습 코드\1. Big Data 분석 기초 실습파일\FITNESS.csv", encoding = 'euc-kr')
FITNESS.head(3)

,NAME,GENDER,AGE,AGEGROUP,WEIGHT,OXY,RUNTIME,RUNPULSE,RSTPULSE,MAXPULSE
0,Donna,여성,42,40대,68.15,59.571,8.17,166,40,172
1,Gracie,여성,38,30대,81.87,60.055,8.63,170,48,186
2,Luanne,여성,43,40대,85.84,54.297,8.65,156,45,168

#### STEP ❷ : groupby, agg를 이용한 평균값 계산

In [45]:
# 몸무게 평균
df_group = FITNESS.groupby(['GENDER', 'AGEGROUP']).agg({'WEIGHT': 'mean'})

df_group

                    WEIGHT
GENDER AGEGROUP
남성     30대       81.080000
       40대       85.465000
       50대       79.426000
여성     30대       78.925000
       40대       72.943750
       50대       70.856667

#### STEP ❸ : pivot을 이용한 변환

In [46]:
# 위에서 계산한거 들고와 (df_group)
df_pivot = df_group.pivot_table(index='GENDER', columns='AGEGROUP', values='WEIGHT')

df_pivot

AGEGROUP     30대       40대        50대
GENDER
남성        81.080  85.46500  79.426000
여성        78.925  72.94375  70.856667

In [47]:
# 위에서 계산한거 들고와 (df_group)
df_pivot = df_group.pivot_table(index='AGEGROUP', columns='GENDER', values='WEIGHT')

df_pivot

GENDER        남성         여성
AGEGROUP
30대       81.080  78.925000
40대       85.465  72.943750
50대       79.426  70.856667